# Generated by Django 5.0.2 on 2024-03-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeesmodule', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='nextofkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=20)),
                ('ID_no', models.CharField(max_length=12)),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
    ]
